name: avaliacao_04
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  sqlite3: ^2.7.6
  sqlite3_flutter_libs: ^0.5.33
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
