name: avaliacao_05
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

dependencies:
  mailer: ^6.0.1  #Pacote para envio de e-mails

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
